# Generated by Django 4.2.5 on 2023-10-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant_families",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Plant_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_name", models.CharField(max_length=200)),
                (
                    "YVR_in_seedDate_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Earliest indoor seed date"
                    ),
                ),
                (
                    "YVR_in_seedDate_stop",
                    models.DateField(
                        blank=True, null=True, verbose_name="Latest indoor seed date"
                    ),
                ),
                (
                    "YVR_out_seedDate_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Earliest outdoor seed date"
                    ),
                ),
                (
                    "YVR_out_seedDate_stop",
                    models.DateField(
                        blank=True, null=True, verbose_name="Latest outdoor seed date"
                    ),
                ),
                (
                    "YVR_tpDate_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Earliest transplant date"
                    ),
                ),
                (
                    "YVR_tpDate_stop",
                    models.DateField(
                        blank=True, null=True, verbose_name="Latest transplant date"
                    ),
                ),
                ("pub_date", models.DateField(verbose_name="date added to DB")),
                (
                    "plants_per_sqf",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Plants per square foot"
                    ),
                ),
                (
                    "family_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.plant_families",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seed_inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed_name", models.CharField(max_length=200)),
                ("size_type", models.CharField(blank=True, default="", max_length=200)),
                ("seed_year", models.PositiveSmallIntegerField(default=2023)),
                (
                    "seed_source",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "seed_link",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("height_cm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("width_cm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pub_date", models.DateField(verbose_name="date added to DB")),
                ("rating", models.IntegerField(default=0)),
                ("seed_notes", models.TextField(blank=True, default="")),
                (
                    "plant_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.plant_info",
                    ),
                ),
            ],
        ),
    ]
