# Generated by Django 4.2.5 on 2023-11-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_plant_families_plant_info_seed_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant_info",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="plant_info",
            name="sun_exposure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_sun", "Full Sun"),
                    ("part_sun", "Part Sun"),
                    ("part_shade", "Part Shade"),
                    ("shade", "Shade"),
                ],
                max_length=20,
                null=True,
                verbose_name="Sun exposure",
            ),
        ),
    ]
