# Generated by Django 4.2.5 on 2024-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_plant_families_plant_info_seed_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="seed_inventory",
            name="OP_F1",
            field=models.CharField(
                blank=True,
                choices=[("F1", "F1"), ("OP", "OP"), ("", "")],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="seed_inventory",
            name="manual_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Personal notes"
            ),
        ),
        migrations.AddField(
            model_name="seed_inventory",
            name="maturity_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="days to maturity"
            ),
        ),
        migrations.AlterField(
            model_name="seed_inventory",
            name="seed_year",
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
