# Generated by Django 4.2.5 on 2024-01-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_seed_inventory_op_f1_seed_inventory_manual_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant_info",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="plant_info",
            name="sun_exposure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full sun", "funn sun"),
                    ("part sun", "part sun"),
                    ("part shade", "part shade"),
                    ("", ""),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
