# Generated by Django 4.2.5 on 2024-01-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_plant_info_notes_plant_info_sun_exposure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant_info",
            name="sun_exposure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full sun", "funn sun"),
                    ("part sun", "part sun"),
                    ("part shade", "part shade"),
                    ("", ""),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
